### ISSUE TITLE
StreamImpl.ReadAsync blocks when State is Closed

### ISSUE THREAD

**Issue by qmfrederik** [Matthias247/http2dotnet#1]
It took me a while to figure this out.

I'm using http2dotnet to make gRPC calls to a server.

When there is no response content, the server closes the connection, so `stream.State` would be `Closed`. 
I was calling `stream.ReadAsync` in the hope that it would return a 0-byte packet with `readDataResult.EndOfStream` set to `true`, but that was not the case.

Instead, the `ReadAsync` call would block forever.

In most .NET APIs, streams which are at the end of the stream return a 0-byte value when reading, and don't block.

**Comment by qmfrederik** [comment]
... on the other hand, it seems `Stream.State` can be set to Closed even when there's data that has been received but not yet read.

**Comment by qmfrederik** [comment]
This code, ugly as it is, seems to do the trick for me. Looks like the gist of it is `readDataPossible` not being set when the stream is closed?

```csharp
var streamImplType = typeof(IStream).Assembly.GetType("Http2.StreamImpl");
var readDataPossibleField = streamImplType.GetField("readDataPossible", BindingFlags.NonPublic | BindingFlags.Instance);
var readDataPossible = (AsyncManualResetEvent)readDataPossibleField.GetValue(stream);
readDataPossible.Set();
```

**Comment by Matthias247** [comment]
> I'm using http2dotnet to make gRPC calls to a server.

That's pretty cool! Exactly one use-case I had for the library, besides general HTTP/2 for web things.

> When there is no response content, the server closes the connection, so stream.State would be Closed.

Do you mean it closes the stream or connection? I'm pretty sure both use-cases are handled and covered by unit-tests. If the server just closes the connection the stream gets cancelled (which is the reset state), and the calling `ReadAsync` should throw a `StreamResetException`.

If the server closes the stream by sending a frame with a EOF flag `readDataResult.EndOfStream` should be set to `true`, as you expected.

Do you have a log that shows which frames the server sends? Enabling logging in the library should provide this.

**Comment by Matthias247** [comment]
Looking at your code it seems like you don't use async/await at all, but  some blocking waits for some calls to the library, and no waits for others. Using proper waits for might fix some strange race conditions that you might encounter. You should be able run your whole logic on the threadpool with async/await like this:

    Task.Run(async () => { await x; await y; return z; }).Result;

**Comment by qmfrederik** [comment]
The code is in [StreamCallInvoker.cs:49-177](https://github.com/qmfrederik/helm/blob/master/src/Helm/Helm/StreamCallInvoker.cs#L49:L177).

You're right that not all calls are awaited - seems the writes are not while the reads are. Not sure it causes the problem but let me try & clean up that code a bit.

**Comment by Matthias247** [comment]
I'm closing this since there was no more activity. If there is any issue on the library, feel free to reopen or create a new issue.
