### ISSUE TITLE
How to handle multipart post from client?

### ISSUE THREAD

**Issue by los93sol** [Matthias247/http2dotnet#7]
I am working with a server that expects the client to perform a post with multipart/form-data.  Each part has it's own headers that go along with it.  I quickly skimmed the source and it looks like this may be a scenario that is not supported, can you point me in the right direction?

**Comment by los93sol** [comment]
Nevermind, I realized that I just need to write them manually into the content of each part and it seems to be working fine that way

**Comment by Matthias247** [comment]
Yes, form encodings (and things like server sent events) are just a special encoding that are applied to the body of HTTP requests/responses, and independent of HTTP/1.1 or HTTP/2. Therefore no dedicated support for those is provided as part of this library.
